spring.datasource.url=jdbc:h2:mem:chatdb_test
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop

application.security.jwt.secret-key=eed9739e4b81a345558172e4b526b7589dd2db76a92ad4a8fd215cd89552432a
application.security.jwt.expiration=900000
application.security.jwt.refresh-token.expiration=2592000000