spring.application.name=ChatMM-backend

spring.profiles.active=dev

# Exclude null fields from all JSON responses to keep them clean and reduce size.
# Could also be done for every DTO individually
spring.jackson.default-property-inclusion=non_null

# WARN
# POSSIBLE org.hibernate.LazyInitializationException
spring.jpa.open-in-view=false

server.servlet.context-path=/api/v1

# Global AuthenticationManager configured with an AuthenticationProvider bean.
# UserDetailsService beans will not be used by Spring Security for automatically configuring username/password login.
# Consider removing the AuthenticationProvider bean. Alternatively, consider using the UserDetailsService in a manually instantiated DaoAuthenticationProvider.
# If the current configuration is intentional, to turn off this warning, increase the logging level of 'org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer' to ERROR
# IT IS INTENTIONAL
logging.level.org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer=ERROR

# 5173: Vite (React/Vue), 3000: React/Next.js
application.security.cors.allowed-origins=${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

application.security.jwt.secret-key=${JWT_SECRET}
application.security.jwt.expiration=${JWT_TOKEN_EXPIRATION:900000}
application.security.jwt.refresh-token.expiration=${REFRESH_TOKEN_EXPIRATION:2592000000}